name: Hello World!

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Run ls -l
        run: |
          ls -l
