name: Deployment pipeline

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  tag_release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_OWNER: RickYCYang
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        with:
          fetch-depth: '0'
